version: '3'
services:
  host_container:
    image: ubuntu:latest
    privileged: true
    networks:
      - mynetwork
    ports:
      - "7007:7007"
    environment:
      - HOST_IP=172.17.0.1
    depends_on:
      - storybook

  storybook:
    image: rafcasto/techdojo-ui-component:$version
    networks:
      - mynetwork
    ports:
      - 6006:6006
    
  
networks:
  mynetwork:
    driver: bridge
      