apiVersion: apps/v1
kind: Deployment
metadata:
  name: storybook-dep
  labels:
    app: storybook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storybook-app
  template:
    metadata:
      labels:
        app: storybook-app
    spec:
      containers:
        - name: storybook
          image: REPO_IMAGE
          env:
          - name: NPM_TOKEN
            value: $NPM_TOKEN
          ports:
            - name: storybook
              containerPort: 6007
