apiVersion: v1
kind: Service
metadata:
  name: storybook-svc
  labels:
    app: storybook-app
spec:
  selector:
    app: storybook-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6006
  type: LoadBalancer
