apiVersion: v1
kind: Service
metadata:
  name: storybook-qa-svc
  labels:
    app: storybook-app-qa
spec:
  selector:
    app: storybook-app-qa
  ports:
    - name: storybook-qa
      protocol: TCP
      port: 6008
      targetPort: storybook-qa
